#!/usr/bin/env python3
"""Generate the 24 thesis-extension benchmark configs programmatically.

Matrix (3 deterministic strategies x 4 support fractions x 2 partition modes = 24):

    strategies: baseline_track_blocks, scan_segment_blocks, station_dropout
    support_fractions: 0.2, 0.4, 0.6, 0.8
    partition_modes: deterministic, adaptive

Each file is a thin overlay on top of ``configs/base.yaml`` with only the
``holdout`` block and a matching ``project.name`` adjusted. Keeping the
configs machine-generated (rather than hand-written) guarantees that the
matrix is exhaustive and free of drift between variants.

Usage:
    python scripts/generate_thesis_extension_configs.py
"""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "configs" / "thesis_extension"

STRATEGIES = (
    "baseline_track_blocks",
    "scan_segment_blocks",
    "station_dropout",
)
SUPPORT_FRACTIONS = (0.2, 0.4, 0.6, 0.8)
PARTITION_MODES = ("deterministic", "adaptive")


def _strategy_short(strategy: str) -> str:
    return {
        "baseline_track_blocks": "bt",
        "scan_segment_blocks": "ss",
        "station_dropout": "sd",
    }[strategy]


def _config_filename(mode: str, strategy: str, alpha: float) -> str:
    return f"{mode}_{_strategy_short(strategy)}_a{int(round(alpha * 100)):02d}.yaml"


def _config_body(mode: str, strategy: str, alpha: float) -> str:
    # We inherit everything else from configs/base.yaml. Only override the
    # holdout block. The partition_mode encoding:
    #   deterministic -> run the listed `strategy` as-is
    #   adaptive      -> replace `strategy` with "learned_oracle_importance"
    #                    at eval time; the listed strategy still governs the
    #                    deterministic reference that the benchmark compares
    #                    against, so we keep it for the record.
    header = dedent(
        f"""\
        # ============================================================================
        # Thesis-extension benchmark config (auto-generated by
        # scripts/generate_thesis_extension_configs.py). Do not edit by hand.
        # ----------------------------------------------------------------------------
        # partition_mode : {mode}
        # strategy       : {strategy}
        # support_fraction: {alpha}
        # ============================================================================

        _inherit_from: configs/base.yaml

        project:
          name: thesis_{mode}_{_strategy_short(strategy)}_a{int(round(alpha*100)):02d}

        holdout:
          enabled: true
          strategy: {strategy}
          support_fraction: {alpha}
          train_support_fractions: [{alpha}]
          eval_support_fractions: [{alpha}]
          partition_mode: {mode}
        """
    )
    if mode == "adaptive":
        header += dedent(
            """\

            # Oracle checkpoint must be supplied at run-time via
            # `--oracle-ckpt <path>` on scripts/run_emc_benchmark.py (or
            # `--oracle-ckpt` on benchmark/run_full_benchmark.py); we do
            # not hardcode a local path here to keep the config relocatable.
            """
        )
    return header


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for mode in PARTITION_MODES:
        for strategy in STRATEGIES:
            for alpha in SUPPORT_FRACTIONS:
                path = OUT_DIR / _config_filename(mode, strategy, alpha)
                path.write_text(_config_body(mode, strategy, alpha), encoding="utf-8")
                written.append(str(path.relative_to(ROOT)))
    print(f"wrote {len(written)} configs to {OUT_DIR.relative_to(ROOT)}")
    for p in written:
        print(f"  {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
